---
- name: Configure roles on web server
  hosts: all
  become: true
  vars:
    web_document_root: "/var/www/teamdigitale.governo.it"
    # NGINX role, see https://galaxy.ansible.com/geerlingguy/nginx/
    nginx_remove_default_vhost: true
    nginx_sendfile: "on"
    nginx_tcp_nopush: "on"
    nginx_tcp_nodelay: "on"
    nginx_server_tokens: "off"
    nginx_ppa_use: true
    nginx_ppa_version: "stable"
    nginx_extra_http_options: |
      gzip on;
      gzip_disable "msie6";
      gzip_vary on;
      gzip_proxied any;
      gzip_comp_level 6;
      gzip_buffers 16 8k;
      gzip_http_version 1.1;
      gzip_min_length 256;
      gzip_types
        application/atom+xml
        application/javascript
        application/json
        application/ld+json
        application/manifest+json
        application/rss+xml
        application/vnd.geo+json
        application/vnd.ms-fontobject
        application/x-font-ttf
        application/x-web-app-manifest+json
        application/xhtml+xml
        application/xml
        font/opentype
        image/bmp
        image/svg+xml
        image/x-icon
        text/cache-manifest
        text/css
        text/plain
        text/vcard
        text/vnd.rim.location.xloc
        text/vtt
        text/x-component
        text/x-cross-domain-policy;
    nginx_vhosts:
      - listen: "443 ssl default_server"
        server_name: "teamdigitale.governo.it"
        root: "{{ web_document_root }}"
        index: "index.html"
        extra_parameters: |
          listen [::]:443 ssl default_server;
          ssl_certificate /etc/ssl/private/teamdigitale_governo_it.crt;
          ssl_certificate_key /etc/ssl/private/teamdigitale_governo_it.key;
          ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
          ssl_ciphers EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
          expires $expires;
          add_header Strict-Transport-Security "max-age=31536000; includeSubdomains;";
          # nginx gzip_static does not add Vary header for fonts.
          location ~* \.(?:eot|ttf|svg)$ {
            expires max;
            add_header Vary Accept-Encoding;
            add_header Cache-Control public;
            access_log off;
          }
          # woff fonts should not be zipped.
          location ~* \.(?:woff|woff2)$ {
            expires max;
            add_header Cache-Control public;
            access_log off;
          }
          include /etc/nginx/conf.d/security_headers.conf;
      - listen: "80 default_server"
        server_name: "teamdigitale.governo.it"
        extra_parameters: |
          listen [::]:80 default_server;
          return 301 https://$server_name$request_uri;
          include /etc/nginx/conf.d/security_headers.conf;

  tasks:
    - name: "NGINX cache expire config map"
      copy:
        content: |
          # Expires map
          map $sent_http_content_type $expires {
              default                    off;
              text/html                  epoch;
              text/css                   max;
              application/javascript     max;
              ~image/                    max;
              ~fonts/                    max;
          }
        dest: /etc/nginx/conf.d/expires_map.conf

    - name: "NGINX extra headers"
      copy:
        content: |
          # Extra security headers
          add_header X-Frame-Options DENY;
          add_header X-Content-Type-Options nosniff;
          add_header X-XSS-Protection "1; mode=block";
          add_header Referrer-Policy "no-referrer";
        dest: "/etc/nginx/conf.d/security_headers.conf"

    - name: "Document root directory"
      file:
        path: "{{ web_document_root }}"
        owner: www-data
        group: www-data
        state: directory
        mode: 0775

  roles:
    - { role: geerlingguy.nginx }
